{% set version = "2.9.20" %}
{% set rc_version = "rc2" %}

package:
  name: libpano13
  version: {{ version }}{{ rc_version }}

source:
  url: https://master.dl.sourceforge.net/project/panotools/libpano13/libpano13-{{ version }}/libpano13-{{ version }}_{{ rc_version }}.tar.gz
  sha256: 6c7184a8af080934252d55e63a0f83457e2b8d59b3b8bb9ad62a21dea82f16cd
  patches:
    - patches/0001-Fixup-copyright-symbol.patch
    - patches/0002-Fixup-uint32-uint32_t.patch
    - patches/0003-Avoid-warning-about-unsigned-char-char-conversion.patch
    - patches/0004-Avoid-uint16-warnings-by-using-uint16_t.patch
    - patches/0005-Deifne-c2pstr-for-mac-aarch64-as-well.patch  # [osx and arm64]

build:
  number: 8
  run_exports:
    - {{ pin_subpackage('libpano13', max_pin='x.x.x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake  # [win]
    - ninja  # [win]
    - make   # [not win]
  host:
    - perl
    - libpng
    - libjpeg-turbo
    - libtiff
    - zlib
    - openjdk
    # hmaarrfk 2020/05/24:
    # GTK3 is an optional dependency, for now lets not build with it.
    # - gtk3

test:
  commands:
    - test -f ${PREFIX}/include/pano13/version.h   # [unix]
    - test -f ${PREFIX}/lib/libpano13${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_INC%\\pano13\\version.h exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\pano13.dll exit 1         # [win]
    - PTinfo -h
    # Opens a GUI on Windows and waits for user to close it, exits with -1
    # anyway :-|
    - panoinfo -help  # [not win]
    - if not exist %LIBRARY_BIN%\\panoinfo.exe exit 1  # [win]

about:
  home: http://panotools.sourceforge.net/

  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: Panorama Tools

  description: |
    This is the pano13 library, part of the Panorama Tools by Helmut
    Dersch of the University of Applied Sciences Furtwangen.

    Also included with the library are
    PToptimizer  a command-line tool for optimizing control points.
    PTmender     a command-line tool for reprojecting images.

extra:
  recipe-maintainers:
    - hmaarrfk
